"""CarConnectivity connector for the Volkswagen EU Data Act portal.

Volkswagen blocked WeConnect API access for 3rd-party integrations. The EU Data
Act portal is the remaining personal-use access path. It delivers a batch
dataset roughly every 15 minutes, is strictly read-only (no commands), and
omits some data points (e.g. GPS location). This connector authenticates
against the portal, downloads the newest dataset per vehicle, and maps the
available data points onto native CarConnectivity attributes as read-only
values.
"""
from __future__ import annotations

from typing import TYPE_CHECKING

import json
import logging
import netrc
import os
import threading
import traceback
from datetime import datetime, timedelta, timezone
from enum import Enum

from carconnectivity.errors import AuthenticationError, RetrievalError, TooManyRequestsError
from carconnectivity.util import config_remove_credentials
from carconnectivity.units import Energy, EnergyConsumption, FuelConsumption, Length, Power, Speed, Temperature
from carconnectivity.attributes import DateAttribute, DurationAttribute, EnumAttribute
from carconnectivity.vehicle import GenericVehicle, ElectricVehicle, CombustionVehicle
from carconnectivity.drive import CombustionDrive, DieselDrive, ElectricDrive, GenericDrive
from carconnectivity.battery import Battery
from carconnectivity.charging import Charging
from carconnectivity.charging_connector import ChargingConnector
from carconnectivity.doors import Doors
from carconnectivity.windows import Windows
from carconnectivity.lights import Lights
from carconnectivity.window_heating import WindowHeatings
from carconnectivity.enums import ConnectionState

from carconnectivity_connectors.base.connector import BaseConnector
try:
    from carconnectivity_connectors.vw_eu_data_act._version import __version__
except ImportError:  # _version.py is generated by setuptools_scm at build time
    __version__ = "0.0.0+unknown"
from carconnectivity_connectors.vw_eu_data_act.client import (
    DEFAULT_BRAND, DEFAULT_COUNTRY, DEFAULT_LANGUAGE, NO_CONTENT_SUFFIX,
    ApiError, AuthError, EudaApiClient,
)
from carconnectivity_connectors.vw_eu_data_act.dataset import (
    Dataset, decikelvin_to_celsius, parse_timestamp, resolve_charge_rate_unit, resolve_distance_unit,
)
from carconnectivity_connectors.vw_eu_data_act.brands import resolve_brand
from carconnectivity_connectors.vw_eu_data_act.vehicle import (
    VWEudaCombustionVehicle, VWEudaElectricVehicle, VWEudaHybridVehicle, VWEudaVehicle,
)

if TYPE_CHECKING:
    from typing import Any, Dict, List, Optional, Tuple
    from carconnectivity.carconnectivity import CarConnectivity
    from carconnectivity.garage import Garage

LOG: logging.Logger = logging.getLogger("carconnectivity.connectors.vw_eu_data_act")
LOG_API: logging.Logger = logging.getLogger("carconnectivity.connectors.vw_eu_data_act-api-debug")

# Datasets land ~every 15 min; refresh shortly after the next expected drop.
DATASET_INTERVAL = timedelta(minutes=15)
POST_DATASET_BUFFER = timedelta(seconds=45)
RETRY_INTERVAL = timedelta(minutes=1)
MIN_INTERVAL = timedelta(seconds=60)

# Map the portal's charge-state enum to the generic CarConnectivity enum.
# Two label spellings are accepted per state: the values originally observed
# from the portal, and the canonical labels from the data dictionary (the
# latter are what an integer index resolves to, see dataset.ENUM_MEMBERS).
CHARGE_STATE_MAPPING: "Dict[str, Charging.ChargingState]" = {
    'CHARGE_STATE_OFF': Charging.ChargingState.OFF,
    'CHARGE_STATE_NOT_READY_FOR_CHARGING': Charging.ChargingState.OFF,
    'CHARGE_STATE_READY_FOR_CHARGING': Charging.ChargingState.READY_FOR_CHARGING,
    'CHARGE_STATE_CHARGING': Charging.ChargingState.CHARGING,
    'CHARGE_STATE_CONSERVATION': Charging.ChargingState.CONSERVATION,
    'CHARGE_STATE_CHARGE_PURPOSE_REACHED_NOT_CONSERVATION_CHARGING': Charging.ChargingState.OFF,
    'CHARGE_STATE_CHARGE_PURPOSE_REACHED_CONSERVATION': Charging.ChargingState.CONSERVATION,
    'CHARGE_STATE_ERROR': Charging.ChargingState.ERROR,
    'CHARGE_STATE_DISCHARGING': Charging.ChargingState.DISCHARGING,
    'CHARGE_STATE_INVALID': Charging.ChargingState.UNKNOWN,
    # Canonical data-dictionary labels (also what enum indices resolve to).
    'CHARGE_STATE_CHARGING_HV_BATTERY': Charging.ChargingState.CHARGING,
    'CHARGE_STATE_CHARGE_PURPOSE_REACHED_AND_NOT_CONSERVATION_CHARGING': Charging.ChargingState.OFF,
    'CHARGE_STATE_CHARGE_PURPOSE_REACHED_AND_CONSERVATION': Charging.ChargingState.CONSERVATION,
    'CHARGE_STATE_CONSERVATION_CHARGING': Charging.ChargingState.CONSERVATION,
    'CHARGE_STATE_CHARGING_ERROR': Charging.ChargingState.ERROR,
}

WINDOW_HEATING_MAPPING: "Dict[str, WindowHeatings.HeatingState]" = {
    'WINDOW_HEATING_STATE_OFF': WindowHeatings.HeatingState.OFF,
    'WINDOW_HEATING_STATE_ON': WindowHeatings.HeatingState.ON,
    'WINDOW_HEATING_STATE_INVALID': WindowHeatings.HeatingState.INVALID,
}

# Map the portal's charge-type enum (what the car is plugged into) to the
# generic CarConnectivity charging-type enum.
CHARGE_TYPE_MAPPING: "Dict[str, Charging.ChargingType]" = {
    'CHARGE_TYPE_INVALID': Charging.ChargingType.INVALID,
    'CHARGE_TYPE_OFF': Charging.ChargingType.OFF,
    'CHARGE_TYPE_AC': Charging.ChargingType.AC,
    'CHARGE_TYPE_DC': Charging.ChargingType.DC,
}


def _charge_rate_per_hour(value: float, unit_enum) -> "Tuple[float, Speed]":
    """Normalise a portal charge rate to a per-hour speed.

    The portal reports the charge rate as range gained over time; the companion
    ``charge_rate_unit`` enum says whether that is km or miles and per hour or
    per minute. The native SpeedAttribute is per-hour only, so per-minute rates
    are scaled by 60. Defaults to km/h when the unit is absent/unrecognised.
    """
    resolved = resolve_charge_rate_unit(unit_enum)
    distance, per_minute = resolved if resolved is not None else ("km", False)
    if per_minute:
        value = value * 60
    return value, Speed.MPH if distance == "mi" else Speed.KMH


def _filename_timestamp(name: str) -> "Optional[datetime]":
    """Parse a YYYYMMDDhhmmss segment from a dataset filename.

    Handles both layouts seen in the wild ("TIMESTAMP_VIN.zip" and
    "VIN_TIMESTAMP.zip") by scanning the underscore-separated parts
    right-to-left for the first one that parses as a timestamp. Only used as a
    fallback when a listing entry lacks ``createdOn``; getting it wrong there
    collapses the newest-dataset sort and can select the wrong dataset.
    """
    stem = name.rsplit(".", 1)[0]
    for part in reversed(stem.split("_")):
        try:
            return datetime.strptime(part, "%Y%m%d%H%M%S").replace(tzinfo=timezone.utc)
        except ValueError:
            continue
    return None


def _created_on(entry: dict) -> "Optional[datetime]":
    """Return the createdOn timestamp of a dataset listing entry."""
    raw = entry.get("createdOn")
    if not raw:
        return _filename_timestamp(entry.get("name", ""))
    parsed = parse_timestamp(raw)
    return parsed if parsed is not None else _filename_timestamp(entry.get("name", ""))


# --- Known mapped fields for detecting unmapped sensors --------------------
KNOWN_MAPPED_FIELDS: set[str] = {
    'mileage.value',
    'mileage.unit',
    'mileage.state',
    'locked',
    'window_heating_state',
    'battery_state_report.soc',
    'range',
    'min_temperature',
    'max_temperature',
    'battery_state_report.charge_power',
    'battery_state_report.charge_rate',
    'battery_state_report.charge_rate_unit',
    'battery_state_report.remaining_charging_time_complete',
    'charging_state_report.current_charge_state',
    'charging_state_report.charge_type',
    'settings.target_soc',
    'settings.charge_mode_selection',
    'car_captured_time',
    # Flat-format (eGolf) fields handled in _map_dataset.
    'mileage',
    'state_of_charge',
    'cruising_range_primary_engine',
    # Maintenance / climate / ambient (mapped in _map_dataset).
    'maintenance_interval__time_until_inspection',
    'maintenance_interval__time_until_oil_change',
    'maintenance_interval_distance_until_inspection',
    'maintenance_interval_distance_until_oil_change',
    'outside_temperature',
    'remaining_climate_time',
    'remaining_climatisation_time',
    # Flat-format charging + consumption (mapped in _map_electric).
    'charging_state',
    'charging_mode',
    'charge_mode_selection_options.manual',
    'charge_mode_selection_options.timer_charging',
    'charge_mode_selection_options.timer_charging_climatization',
    'charge_mode_selection_options.preferred_charging_times',
    'charge_mode_selection_options.only_own_current',
    'charge_mode_selection_options.home_storage_charging',
    'charge_mode_selection_options.immediate_charging',
    'charge_mode_selection_options.immediate_discharging',
    'plug_state',
    'external_power_supply_state',
    'remaining_charging_time',
    'charging_power',
    'actual_charge_rate',
    'charge_rate_unit',
    'long_term_data_average_electr_engine_consumption',
    # Combustion / PHEV (mapped in _map_combustion).
    'fuel_level_current_level',
    'tank_current_level',
    'long_term_data_average_fuel_consumption',
    'cruising_range_secondary_engine',
    'cruising_range_combined',
    'scr_range',
    'oil_level_actual_level',
    # Door / window / light status (mapped in _map_status).
    'window_heating_state_front',
    'window_heating_state_rear',
    'lock_state',
    'parking_lights',
    'parking_brake',
    'open_state_front_left_door', 'open_state_front_right_door',
    'open_state_rear_left_door', 'open_state_rear_right_door',
    'open_state_front_engine_bonnet', 'open_state_tailgate',
    'locked_state_front_left_door', 'locked_state_front_right_door',
    'locked_state__rear_left_door', 'locked_state_rear_right_door',
    'locked_state_front_engine_bonnet', 'locked_state_tailgate',
    'state_front_left_door_window_lifter', 'state_front_right_door_window_lifter',
    'state_rear_left_door_window_lifter', 'state_rear_right_door_window_lifter',
    'state_sunroof_motor_hood_1',
    'position_front_left_door_window_lifter', 'position_front_right_door_window_lifter',
    'position_rear_left_door_window_lifter', 'position_rear_right_door_window_lifter',
    'position_sunroof_motor_hood_1',
}

# Field-name prefixes whose subtree is mapped even though the exact leaf name is
# not pinned (e.g. energy_contents.maximal_energy_content.<leaf>, mapped by
# prefix). Excluded from the unmapped-sensor detection like KNOWN_MAPPED_FIELDS.
KNOWN_MAPPED_PREFIXES: "Tuple[str, ...]" = (
    'energy_contents.maximal_energy_content',
)

# Portal door id -> (open_state field, locked_state field). Note the double
# underscore in the rear-left lock field (portal quirk).
_DOOR_FIELDS: "Dict[str, Tuple[str, str]]" = {
    'front_left': ('open_state_front_left_door', 'locked_state_front_left_door'),
    'front_right': ('open_state_front_right_door', 'locked_state_front_right_door'),
    'rear_left': ('open_state_rear_left_door', 'locked_state__rear_left_door'),
    'rear_right': ('open_state_rear_right_door', 'locked_state_rear_right_door'),
    'bonnet': ('open_state_front_engine_bonnet', 'locked_state_front_engine_bonnet'),
    'tailgate': ('open_state_tailgate', 'locked_state_tailgate'),
}

# Portal window id -> (opening-percentage field, open/closed state field).
# The portal exposes both: position_* is the opening percentage (unit '%', 0 =
# closed) and state_* is the coarse open/closed code. We prefer the percentage
# because it also lets us tell a partly-open (ajar) window from a fully open one;
# state_* is the fallback when the percentage is missing.
_WINDOW_FIELDS: "Dict[str, Tuple[str, str]]" = {
    'front_left': ('position_front_left_door_window_lifter', 'state_front_left_door_window_lifter'),
    'front_right': ('position_front_right_door_window_lifter', 'state_front_right_door_window_lifter'),
    'rear_left': ('position_rear_left_door_window_lifter', 'state_rear_left_door_window_lifter'),
    'rear_right': ('position_rear_right_door_window_lifter', 'state_rear_right_door_window_lifter'),
    'sunroof': ('position_sunroof_motor_hood_1', 'state_sunroof_motor_hood_1'),
}


def _open_code(value) -> "Optional[str]":
    """Decode the portal 'open' encoding: 2 = open, 3 = closed, 0/1 = invalid."""
    if value == 2:
        return 'open'
    if value == 3:
        return 'closed'
    return None


def _window_open_code(position, state) -> "Optional[str]":
    """Decode a window opening from the portal.

    The percentage (position_*, 0..100) is preferred: 0 = closed, 100 = open,
    anything in between = ajar (CarConnectivity has no numeric window position,
    only an open/closed/ajar enum). When the percentage is absent or out of range
    fall back to the coarse state_* open/closed code.
    """
    try:
        pct = float(position)
    except (TypeError, ValueError):
        pct = None
    if pct is not None and 0 <= pct <= 100:
        if pct <= 0:
            return 'closed'
        if pct >= 100:
            return 'open'
        return 'ajar'
    return _open_code(state)


def _lock_code(value) -> "Optional[str]":
    """Decode the portal 'open' encoding for locks: 2 = locked, 3 = unlocked."""
    if value == 2:
        return 'locked'
    if value == 3:
        return 'unlocked'
    return None


class VWEudaChargeMode(Enum):
    """Selected charge mode reported by the portal (``charge_mode_selection``).

    Read-only. The field is the *selected* charge mode (one of its values is
    itself ``preferred_charging_times``), so the attribute is named ``charge_mode``
    rather than "preferred". Member names/values follow the EU Data Act data
    dictionary options and mirror the seatcupra/skoda connector enum, so consumers
    see a consistent set across brands.
    """
    MANUAL = 'manual'
    TIMER = 'timer'
    TIMER_CHARGING_WITH_CLIMATISATION = 'timer_charging_with_climatisation'
    PREFERRED_CHARGING_TIMES = 'preferred_charging_times'
    ONLY_OWN_CURRENT = 'only_own_current'
    HOME_STORAGE_CHARGING = 'home_storage_charging'
    IMMEDIATE_CHARGING = 'immediate_charging'
    IMMEDIATE_DISCHARGING = 'immediate_discharging'
    OFF = 'off'
    INVALID = 'invalid'
    UNKNOWN = 'unknown charge mode'


# Dotted format: a single 'settings.charge_mode_selection' value. Normalised token
# (upper-case, optional CHARGE_MODE_SELECTION_ prefix stripped) -> enum.
_CHARGE_MODE_TOKENS = {
    'MANUAL': VWEudaChargeMode.MANUAL,
    'TIMER': VWEudaChargeMode.TIMER,
    'TIMERCHARGING': VWEudaChargeMode.TIMER,
    'TIMER_CHARGING': VWEudaChargeMode.TIMER,
    'IMMEDIATECHARGING': VWEudaChargeMode.IMMEDIATE_CHARGING,
    'IMMEDIATE_CHARGING': VWEudaChargeMode.IMMEDIATE_CHARGING,
    'TIMER_CHARGING_CLIMATIZATION': VWEudaChargeMode.TIMER_CHARGING_WITH_CLIMATISATION,
    'TIMER_CHARGING_CLIMATISATION': VWEudaChargeMode.TIMER_CHARGING_WITH_CLIMATISATION,
    'TIMER_CHARGING_WITH_CLIMATISATION': VWEudaChargeMode.TIMER_CHARGING_WITH_CLIMATISATION,
    'PREFERRED_CHARGING_TIMES': VWEudaChargeMode.PREFERRED_CHARGING_TIMES,
    'ONLY_OWN_CURRENT': VWEudaChargeMode.ONLY_OWN_CURRENT,
    'HOME_STORAGE_CHARGING': VWEudaChargeMode.HOME_STORAGE_CHARGING,
    'IMMEDIATE_DISCHARGING': VWEudaChargeMode.IMMEDIATE_DISCHARGING,
    'OFF': VWEudaChargeMode.OFF,
    'INVALID': VWEudaChargeMode.INVALID,
}

# Flat/continuous format: one boolean per option
# (charge_mode_selection_options.<suffix>); the active one wins.
_CHARGE_MODE_FLAT = {
    'manual': VWEudaChargeMode.MANUAL,
    'timer_charging': VWEudaChargeMode.TIMER,
    'timer_charging_climatization': VWEudaChargeMode.TIMER_CHARGING_WITH_CLIMATISATION,
    'preferred_charging_times': VWEudaChargeMode.PREFERRED_CHARGING_TIMES,
    'only_own_current': VWEudaChargeMode.ONLY_OWN_CURRENT,
    'home_storage_charging': VWEudaChargeMode.HOME_STORAGE_CHARGING,
    'immediate_charging': VWEudaChargeMode.IMMEDIATE_CHARGING,
    'immediate_discharging': VWEudaChargeMode.IMMEDIATE_DISCHARGING,
}


def _charge_mode(raw) -> "Optional[VWEudaChargeMode]":
    """Normalise a dotted ``charge_mode_selection`` value to VWEudaChargeMode.

    Returns None when there is nothing to map (absent/empty) and ``UNKNOWN`` when
    a value is present but unrecognised, so a new value is surfaced rather than
    silently dropped.
    """
    if raw is None:
        return None
    token = str(raw).strip().upper()
    if not token:
        return None
    if token.startswith('CHARGE_MODE_SELECTION_'):
        token = token[len('CHARGE_MODE_SELECTION_'):]
    return _CHARGE_MODE_TOKENS.get(token, VWEudaChargeMode.UNKNOWN)


def _charge_mode_flat(dataset) -> "Optional[VWEudaChargeMode]":
    """Pick the active charge mode from the flat per-option booleans."""
    for suffix, mode in _CHARGE_MODE_FLAT.items():
        value = dataset.value_of(f'charge_mode_selection_options.{suffix}')
        if value is None:
            continue
        if isinstance(value, bool):
            active = value
        elif isinstance(value, (int, float)):
            active = value != 0
        else:
            active = str(value).strip().lower() in ('true', '1', 'yes', 'on')
        if active:
            return mode
    return None


def _light_code(value) -> "Optional[str]":
    """Decode the portal 'lights' encoding: 2 = off, 3/4/5 = on, 0/1 = invalid."""
    if value in (0, 1):
        return None
    if value == 2:
        return 'off'
    if value in (3, 4, 5):
        return 'on'
    return None


class Connector(BaseConnector):
    """Read-only connector for the Volkswagen EU Data Act portal."""

    def __init__(self, connector_id: str, car_connectivity: CarConnectivity, config: Dict, *args,
                 initialization: Optional[Dict] = None, **kwargs) -> None:
        # ``initialization`` is accepted because newer carconnectivity cores pass
        # it when loading connectors, but it is deliberately NOT forwarded to
        # BaseConnector: on those cores the base __init__ chain does not accept it
        # and raises "TypeError: ...__init__() got an unexpected keyword argument
        # 'initialization'". It is not needed for this read-only connector. (#1)
        BaseConnector.__init__(self, connector_id=connector_id, car_connectivity=car_connectivity, config=config,
                               log=LOG, api_log=LOG_API, *args, **kwargs)

        self._background_thread: Optional[threading.Thread] = None
        self._stop_event = threading.Event()
        # Per-VIN data-request identifier, resolved lazily from the metadata endpoint.
        self._identifiers: Dict[str, str] = {}
        # Per-VIN name of the newest data-bearing dataset already downloaded and
        # mapped, so intervals that produced only a "no content" zip don't trigger
        # a redundant re-download of the same dataset.
        self._last_dataset: Dict[str, str] = {}
        # Tracks whether the initial bootstrap (download all zips, build cache) has run per VIN.
        self._bootstrapped: set[str] = set()
        # Merged dataset per VIN tracking the latest value per field across all downloaded zips.
        self._merged_datasets: Dict[str, Dataset] = {}
        # VINs whose on-demand ('all') historical recon dump has already been written.
        self._historical_done: "set[str]" = set()
        # Set of field names already observed per VIN (used to detect new/unmapped sensors).
        self._observed_fields: Dict[str, set] = {}

        self.connection_state: EnumAttribute[ConnectionState] = EnumAttribute(
            name="connection_state", parent=self, value_type=ConnectionState,
            value=ConnectionState.DISCONNECTED, tags={'connector_custom'})
        self.interval: DurationAttribute = DurationAttribute(name="interval", parent=self, tags={'connector_custom'})
        self.interval.minimum = MIN_INTERVAL
        self.interval._is_changeable = True  # pylint: disable=protected-access

        LOG.info("Loading vw_eu_data_act connector with config %s", config_remove_credentials(config))

        # --- credentials (config dict or .netrc) ---
        self.active_config['username'] = None
        self.active_config['password'] = None
        if 'username' in config and 'password' in config:
            self.active_config['username'] = config['username']
            self.active_config['password'] = config['password']
        else:
            if 'netrc' in config:
                self.active_config['netrc'] = config['netrc']
            else:
                self.active_config['netrc'] = os.path.join(os.path.expanduser("~"), ".netrc")
            try:
                secrets = netrc.netrc(file=self.active_config['netrc'])
                secret = secrets.authenticators("vw_eu_data_act")
                if secret is None:
                    raise AuthenticationError(
                        f'Authentication using {self.active_config["netrc"]} failed: vw_eu_data_act not found in netrc')
                self.active_config['username'], _, self.active_config['password'] = secret
            except netrc.NetrcParseError as err:
                raise AuthenticationError(f'Authentication using {self.active_config["netrc"]} failed: {err}') from err
            except FileNotFoundError as err:
                raise AuthenticationError(
                    f'{self.active_config["netrc"]} netrc-file was not found. '
                    'Create it or provide username and password in config') from err

        if self.active_config['username'] is None or self.active_config['password'] is None:
            raise AuthenticationError('Username or password not provided')

        # --- interval ---
        self.active_config['interval'] = 900
        if 'interval' in config and config['interval'] is not None:
            self.active_config['interval'] = config['interval']
            if self.active_config['interval'] < MIN_INTERVAL.total_seconds():
                raise ValueError(f'Interval must be at least {int(MIN_INTERVAL.total_seconds())} seconds')
        self.interval._set_value(timedelta(seconds=self.active_config['interval']))  # pylint: disable=protected-access

        # --- OIDC state (country/language/brand) ---
        self.active_config['country'] = config.get('country', DEFAULT_COUNTRY)
        self.active_config['language'] = config.get('language', DEFAULT_LANGUAGE)
        self.active_config['brand'] = config.get('brand', DEFAULT_BRAND)

        # Opt-in: accept a pending terms-and-conditions/data-privacy document
        # during login instead of failing (issue #15). Off by default because it
        # accepts a legal document on the user's behalf.
        self.active_config['accept_terms_on_login'] = bool(config.get('accept_terms_on_login', False))

        # --- hidden VINs ---
        if 'hide_vins' in config and config['hide_vins'] is not None:
            self.active_config['hide_vins'] = config['hide_vins']
        else:
            self.active_config['hide_vins'] = []

        # Optional explicit VIN allow-list (otherwise all consented vehicles are used).
        self.active_config['vin'] = config.get('vin')

        # --- on-demand ('all') historical export dump (opt-in diagnostic, off by default) ---
        # When enabled, the connector fetches the on-demand historical export once
        # per VIN and writes the raw JSON to historical_dump_path for inspection.
        # No mapping is done: this is a diagnostic only. NOTE (verified on a real
        # VW-group export): the 'all' package is the raw backend account dump
        # (charger/timer/climater settings, remote lock-action history, trip
        # mileage history, sync metadata; domains RBC/RDT/RPC/RLU/PSO/RTS/OTV). It
        # does NOT contain a live sensor feed and, in particular, NO location /
        # ParkingPosition. So there is no GPS to map here, matching the module
        # docstring; the dump is kept to document what 'all' actually returns.
        self.active_config['historical'] = bool(config.get('historical', False))
        self.active_config['historical_dump_path'] = config.get(
            'historical_dump_path', 'vw_eu_data_act.historical-sample.json')

        self.client: EudaApiClient = EudaApiClient(
            email=self.active_config['username'], password=self.active_config['password'],
            country=self.active_config['country'], language=self.active_config['language'],
            brand=self.active_config['brand'],
            accept_terms_on_login=self.active_config['accept_terms_on_login'])

    # -- lifecycle ---------------------------------------------------------

    def startup(self) -> None:
        self._background_thread = threading.Thread(target=self._background_loop, daemon=False)
        self._background_thread.name = 'carconnectivity.connectors.vw_eu_data_act-background'
        self._background_thread.start()
        self.healthy._set_value(value=True)  # pylint: disable=protected-access

    def _background_loop(self) -> None:
        self._stop_event.clear()
        fetch: bool = True
        self.connection_state._set_value(value=ConnectionState.CONNECTING)  # pylint: disable=protected-access
        while not self._stop_event.is_set():
            interval: float = self.active_config['interval']
            try:
                try:
                    if fetch:
                        self.fetch_all()
                        fetch = False
                    else:
                        self.update_vehicles()
                    self.last_update._set_value(value=datetime.now(tz=timezone.utc))  # pylint: disable=protected-access
                    if self.interval.value is not None:
                        interval = self.interval.value.total_seconds()
                except Exception:
                    self.connection_state._set_value(value=ConnectionState.ERROR)  # pylint: disable=protected-access
                    if self.interval.value is not None:
                        interval = self.interval.value.total_seconds()
                    raise
            except TooManyRequestsError as err:
                LOG.error('Too many requests from your account (%s). Will try again after 15 minutes', str(err))
                self.connection_state._set_value(value=ConnectionState.ERROR)  # pylint: disable=protected-access
                self._stop_event.wait(900)
            except (RetrievalError, ApiError) as err:
                # A failed poll (transient network/DNS blip, a stale data-request
                # identifier, etc.) should recover on the next short cycle rather
                # than freezing the data for the full ~15-min cadence: retry within
                # ~1 min. The next successful update reschedules to the normal
                # cadence via _reschedule(). (HA f129ebc)
                interval = RETRY_INTERVAL.total_seconds()
                self.interval._set_value(RETRY_INTERVAL)  # pylint: disable=protected-access
                LOG.error('Retrieval error during update (%s). Will try again after %ss', str(err), interval)
                self.connection_state._set_value(value=ConnectionState.ERROR)  # pylint: disable=protected-access
                self._stop_event.wait(interval)
            except Exception:  # pylint: disable=broad-exception-caught
                # Never let an unexpected error kill the polling thread: log it,
                # mark unhealthy, and retry on the next interval so the connector
                # self-heals once the underlying issue clears.
                LOG.critical('Unexpected error during update (will retry in %ss): %s', interval, traceback.format_exc())
                self.healthy._set_value(value=False)  # pylint: disable=protected-access
                self.connection_state._set_value(value=ConnectionState.ERROR)  # pylint: disable=protected-access
                self._stop_event.wait(interval)
            else:
                self.connection_state._set_value(value=ConnectionState.CONNECTED)  # pylint: disable=protected-access
                if self.healthy.value is not True:
                    self.healthy._set_value(value=True)  # pylint: disable=protected-access
                self._stop_event.wait(interval)
        self.connection_state._set_value(value=ConnectionState.DISCONNECTED)  # pylint: disable=protected-access

    def shutdown(self) -> None:
        for vehicle in self.car_connectivity.garage.list_vehicles():
            if len(vehicle.managing_connectors) == 1 and self in vehicle.managing_connectors:
                self.car_connectivity.garage.remove_vehicle(vehicle.id)
                vehicle.enabled = False
        self._stop_event.set()
        self.client.close()
        if self._background_thread is not None:
            self._background_thread.join()
        BaseConnector.shutdown(self)

    # -- fetching ----------------------------------------------------------

    def fetch_all(self) -> None:
        """Discover vehicles from the portal, then update them."""
        garage: Garage = self.car_connectivity.garage
        vehicles: List[dict] = self.client.list_vehicles()
        seen_vins: set[str] = set()
        allow_vins = {self.active_config['vin']} if self.active_config['vin'] else None
        for veh in vehicles:
            vin = veh.get('vin')
            if vin is None:
                continue
            if vin in self.active_config['hide_vins']:
                LOG.info('Vehicle %s filtered out due to configuration', vin)
                continue
            if allow_vins is not None and vin not in allow_vins:
                continue
            seen_vins.add(vin)
            vehicle: Optional[VWEudaVehicle] = garage.get_vehicle(vin)  # pyright: ignore[reportAssignmentType]
            if vehicle is None:
                vehicle = VWEudaVehicle(vin=vin, garage=garage, managing_connector=self,
                                        initialization=garage.get_initialization(vin))
                # Label the manufacturer from the configured brand (Volkswagen,
                # Audi, Skoda, SEAT, Cupra, Bentley, ...) instead of always "Volkswagen".
                vehicle.manufacturer._set_value(  # pylint: disable=protected-access
                    resolve_brand(self.active_config['brand']).manufacturer)
                garage.add_vehicle(vin, vehicle)
            if veh.get('nickname'):
                vehicle.name._set_value(veh['nickname'])  # pylint: disable=protected-access
        # Remove vehicles no longer present that are managed solely by us.
        for vin in set(garage.list_vehicle_vins()) - seen_vins:
            vehicle_to_remove = garage.get_vehicle(vin)
            if vehicle_to_remove is not None and vehicle_to_remove.is_managed_by_connector(self):
                garage.remove_vehicle(vin)
        self.update_vehicles()

    def update_vehicles(self) -> None:
        """Download the newest dataset for each managed vehicle and map it."""
        garage: Garage = self.car_connectivity.garage
        next_polls: List[datetime] = []
        for vin in garage.list_vehicle_vins():
            vehicle = garage.get_vehicle(vin)
            if vehicle is None or not vehicle.is_managed_by_connector(self):
                continue
            newest_created = self._update_vehicle(vin)
            if newest_created is not None:
                next_polls.append(newest_created + DATASET_INTERVAL + POST_DATASET_BUFFER)
        self._reschedule(next_polls)
        # Flush accumulated notifications so on_transaction_end observers (e.g. the
        # mqtt_homeassistant plugin's discovery publisher) fire. Without this, newly
        # enabled attributes are never announced and HA entities stay "unavailable".
        self.car_connectivity.transaction_end()

    def _refresh_identifier(self, vin: str) -> "Optional[str]":
        """(Re-)fetch the data-request identifier from the metadata endpoint.

        Returns the identifier and updates the cache when the portal hands out a
        *new* one (e.g. after the continuous data subscription was deleted and
        recreated, which assigns a fresh identifier and silently invalidates the
        stored one). Returns ``None`` when it is unavailable or unchanged.
        """
        try:
            meta = self.client.get_metadata(vin)
        except ApiError as err:
            LOG.debug('Could not refresh data-request identifier for %s: %s', vin, err)
            return None
        new_id = meta.get('Identifier') or meta.get('identifier')
        if not new_id or new_id == self._identifiers.get(vin):
            return None
        if vin in self._identifiers:
            LOG.warning('Data-request identifier for %s changed (%s -> %s); the portal '
                        'subscription was likely recreated. Using the new identifier.',
                        vin, self._identifiers[vin], new_id)
        self._identifiers[vin] = new_id
        return new_id

    def _list_datasets_with_refresh(self, vin: str, identifier: str) -> "Tuple[List[dict], str]":
        """List datasets, self-healing a stale identifier once if needed.

        A recreated subscription makes the stored identifier stale: the listing
        then errors or comes back empty. On either signal, re-fetch the
        identifier and retry once before giving up, so the connector recovers
        automatically on the next cycle without a manual reload. The metadata
        call only happens on that failure/empty signal, so there is no extra API
        load in normal operation. (HA 2c979c7, issue #13)
        """
        listing: "List[dict]" = []
        for retried in (False, True):
            try:
                listing = self.client.list_datasets(vin, identifier)
            except ApiError:
                if not retried:
                    new_id = self._refresh_identifier(vin)
                    if new_id is not None:
                        identifier = new_id
                        continue
                raise
            # An empty listing can also mean the subscription was recreated.
            if not listing and not retried:
                new_id = self._refresh_identifier(vin)
                if new_id is not None:
                    identifier = new_id
                    continue
            break
        return listing, identifier

    def _update_vehicle(self, vin: str) -> "Optional[datetime]":
        """Fetch and map the newest dataset for ``vin``; return its createdOn.

        On the first call per VIN (bootstrap), downloads ALL available ZIP files
        chronologically, merges their values field-by-field (latest wins), and maps
        the merged dataset onto CarConnectivity attributes. Detects field names
        that are not yet mapped and logs them as new/unmapped sensors.

        Returns the createdOn of the newest *listing entry* (content or "no
        content"), which marks the delivery cadence and drives the reschedule:
        the portal emits one zip per ~15-min interval, so the next one is due
        ~15 min after the newest one regardless of whether it carried data.
        Returns ``None`` only when there is nothing dated to schedule from
        (empty/unprovisioned listing), in which case the caller retries soon.
        """
        identifier = self._identifiers.get(vin)
        if identifier is None:
            identifier = self._refresh_identifier(vin)
            if identifier is None:
                LOG.warning('No data-request identifier for vehicle %s; skipping', vin)
                return None

        listing, identifier = self._list_datasets_with_refresh(vin, identifier)
        # All named entries, oldest -> newest by createdOn (or filename fallback).
        dated = sorted(
            ((e, _created_on(e)) for e in listing if e.get('name')),
            key=lambda pair: pair[1] or datetime.min.replace(tzinfo=timezone.utc),
        )

        if not dated:
            return None

        newest_created = dated[-1][1]

        # Download and map the newest data-bearing dataset. A "no content" zip
        # for the latest interval means there is simply no data this interval
        # (not an error or an overdue dataset), so we keep the last known values
        # and still reschedule ~15 min out from newest_created below. Skip the
        # download when that dataset is the one we already mapped last time.
        content = [e for e, _ in dated if not e['name'].endswith(NO_CONTENT_SUFFIX)]
        if not content:
            LOG.debug('Latest dataset for %s carries no content; waiting for the next interval', vin)
            return newest_created

        if vin not in self._bootstrapped:
            self._bootstrap_vehicle(vin, identifier, content)
            if vin in self._merged_datasets:
                self._last_dataset[vin] = content[-1]['name']

        newest = content[-1]
        if self._last_dataset.get(vin) != newest['name']:
            payload = self.client.download_dataset(vin, identifier, newest['name'])
            dataset = Dataset.from_json(payload)
            self._map_dataset(vin, dataset, _created_on(newest))
            self._last_dataset[vin] = newest['name']
        self._historical_recon(vin)
        return newest_created

    def _historical_recon(self, vin: str) -> None:
        """Opt-in one-shot diagnostic dump of the on-demand ('all') historical export.

        Fetches the historical package (same endpoints, request_type='all') and
        writes the raw JSON to ``historical_dump_path`` so it can be inspected. No
        mapping is done: a real VW-group export was found to be the raw backend
        account dump (settings/timers/lock-action + trip-mileage history), with no
        live sensor feed and no location, so there is nothing to map onto native
        attributes. Kept purely to document what 'all' returns. Robust to the
        export not being generated yet (empty list / 404 / missing identifier ->
        debug log, no raise), so it simply retries on a later cycle.
        """
        if not self.active_config.get('historical') or vin in self._historical_done:
            return
        try:
            meta = self.client.get_metadata(vin, request_type='all')
            identifier = (meta or {}).get('Identifier') or (meta or {}).get('identifier')
            if not identifier:
                LOG.debug('Historical recon %s: no identifier yet (export not generated?)', vin)
                return
            listing = self.client.list_datasets(vin, identifier, request_type='all')
            content = [e for e in listing if isinstance(e, dict) and e.get('name')
                       and not e['name'].endswith(NO_CONTENT_SUFFIX)]
            if not content:
                LOG.debug('Historical recon %s: no on-demand dataset available yet', vin)
                return
            newest = content[-1]['name']
            payload = self.client.download_dataset(vin, identifier, newest, request_type='all')
            path = self.active_config['historical_dump_path']
            with open(path, 'w', encoding='utf-8') as handle:
                json.dump(payload, handle, indent=2, ensure_ascii=False)
            self._historical_done.add(vin)
            LOG.info('Historical on-demand export for %s written to %s (%d data points) for inspection.',
                     vin, os.path.abspath(path), len(payload.get('Data', []) if isinstance(payload, dict) else []))
        except (ApiError, RetrievalError, OSError, ValueError) as err:
            LOG.debug('Historical recon %s failed (will retry next cycle): %s', vin, err)

    def _bootstrap_vehicle(self, vin: str, identifier: str, listing: list) -> None:
        """Download all available ZIP datasets for ``vin``, merge chronologically,
        map the merged result, and mark the vehicle as bootstrapped."""
        LOG.info('Bootstrapping vehicle %s: downloading %d datasets', vin, len(listing))
        datasets: list = []
        for entry in listing:
            name = entry['name']
            try:
                payload = self.client.download_dataset(vin, identifier, name)
                datasets.append(Dataset.from_json(payload))
                LOG.debug('Bootstrap %s: downloaded %s', vin, name)
            except ApiError as err:
                LOG.warning('Bootstrap %s: failed to download %s: %s', vin, name, err)
        if not datasets:
            LOG.warning('Bootstrap %s: no datasets could be downloaded', vin)
            self._bootstrapped.add(vin)
            return

        merged = Dataset.merge(datasets)
        self._merged_datasets[vin] = merged
        self._observed_fields[vin] = set(merged.field_names)
        self._detect_unmapped_fields(vin, merged)
        self._map_dataset(vin, merged, _created_on(listing[-1]) if listing else None)
        self._bootstrapped.add(vin)
        LOG.info('Bootstrapped vehicle %s: merged %d datasets, %d unique fields',
                 vin, len(datasets), len(merged.field_names))

    @staticmethod
    def _detect_unmapped_fields(vin: str, dataset: Dataset) -> None:
        """Log any field names in the dataset that are not yet mapped to CarConnectivity."""
        unmapped = {f for f in dataset.field_names
                    if f not in KNOWN_MAPPED_FIELDS and not f.startswith(KNOWN_MAPPED_PREFIXES)}
        for field in sorted(unmapped):
            dp = dataset.by_field(field)
            raw = dp.raw_value if dp else '?'
            LOG.info('New unmapped sensor for %s: field=%s value=%s', vin, field, raw)

    # -- mapping -----------------------------------------------------------

    def _map_dataset(self, vin: str, dataset: Dataset, created_on: Optional[datetime] = None) -> None:
        """Map an EU Data Act dataset onto native CarConnectivity attributes (read-only).

        ``created_on`` is the portal createdOn of the mapped dataset, used as the
        freshness fallback when the data format carries no per-field timestampUtc."""
        garage: Garage = self.car_connectivity.garage
        vehicle: Optional[VWEudaVehicle] = garage.get_vehicle(vin)  # pyright: ignore[reportAssignmentType]
        if vehicle is None:
            return
        captured_at = dataset.captured_at

        # Detect the drivetrain from which data the portal reports and promote the
        # vehicle to the matching subclass. There is no single "powertrain" field
        # and the field set varies by platform/format, so we detect by presence:
        #   - electric: battery SoC / charge power / charge state / electric range
        #   - fuel:     fuel level / petrol consumption
        # A car reporting both is a plug-in hybrid (PHEV). Promotion only ever moves
        # "up" (Hybrid is a subclass of both Electric and Combustion), so a partial
        # dataset never demotes an already-richer vehicle.
        has_electric = any(dataset.by_field(f) is not None for f in (
            'battery_state_report.soc', 'battery_state_report.charge_power',
            'charging_state_report.current_charge_state', 'state_of_charge',
            'cruising_range_secondary_engine'))
        has_fuel = any(dataset.by_field(f) is not None for f in (
            'fuel_level_current_level', 'tank_current_level',
            'long_term_data_average_fuel_consumption', 'short_term_data_average_fuel_consumption'))
        # A pure EV in flat format reports only cruising_range_primary_engine (its
        # electric range) with no fuel fields; treat that as electric.
        if not has_electric and not has_fuel \
                and dataset.by_field('cruising_range_primary_engine') is not None:
            has_electric = True

        # "already" tests the CarConnectivity base capabilities (HybridVehicle is
        # both an ElectricVehicle and a CombustionVehicle), so a partial dataset
        # never demotes a richer vehicle.
        if has_electric and has_fuel:
            desired, desired_type = VWEudaHybridVehicle, GenericVehicle.Type.HYBRID
            already = isinstance(vehicle, ElectricVehicle) and isinstance(vehicle, CombustionVehicle)
        elif has_electric:
            desired, desired_type = VWEudaElectricVehicle, GenericVehicle.Type.ELECTRIC
            already = isinstance(vehicle, ElectricVehicle)
        elif has_fuel:
            desired, desired_type = VWEudaCombustionVehicle, GenericVehicle.Type.GASOLINE
            already = isinstance(vehicle, CombustionVehicle)
        else:
            desired, desired_type, already = None, None, True
        if desired is not None and not already:
            LOG.debug('Promoting %s to %s for %s', vehicle.__class__.__name__, desired.__name__, vin)
            vehicle = desired(garage=garage, origin=vehicle)
            garage.replace_vehicle(vin, vehicle)
            vehicle.type._set_value(desired_type)  # pylint: disable=protected-access
        is_phev = has_electric and has_fuel

        # Dataset freshness, exposed PER VEHICLE: one connector serves several VINs,
        # each with its own capture time, so this cannot live on the connector. It is
        # (re)created lazily on the current instance because the promotion above swaps
        # in a subclass that does not carry custom attributes over. The base MQTT
        # plugin auto-publishes it, so it can back a `device_class: timestamp` sensor.
        # Prefer the precise per-measurement time (max timestampUtc); fall back to the
        # dataset's createdOn when the portal format carries no field timestamps.
        freshness = captured_at or created_on
        if freshness is not None:
            cap_attr = getattr(vehicle, 'captured_at', None)
            if not isinstance(cap_attr, DateAttribute):
                cap_attr = DateAttribute(name='captured_at', parent=vehicle, tags={'connector_custom'})
                vehicle.captured_at = cap_attr
            if cap_attr.value is None or freshness > cap_attr.value:
                cap_attr._set_value(value=freshness)  # pylint: disable=protected-access

        # Odometer (mileage.value). The portal reports km or miles depending on
        # the vehicle; the unit comes from the companion mileage.unit enum, with
        # km as the fallback when that field is absent. Prefer the highest slot
        # among equally-fresh readings so a lagging snapshot never makes the
        # (monotonic) odometer momentarily read low.
        mileage = dataset.freshest_max_value_of('mileage.value')
        if mileage is not None:
            mileage_unit = Length.MI if resolve_distance_unit(dataset.value_of('mileage.unit')) == 'mi' else Length.KM
            vehicle.odometer._set_value(value=mileage, measured=captured_at, unit=mileage_unit)  # pylint: disable=protected-access
            vehicle.odometer.precision = 1

        # Doors lock state
        locked = dataset.value_of('locked')
        if isinstance(locked, bool):
            vehicle.doors.lock_state._set_value(  # pylint: disable=protected-access
                Doors.LockState.LOCKED if locked else Doors.LockState.UNLOCKED, measured=captured_at)

        # Window heating state
        wh = dataset.value_of('window_heating_state')
        if isinstance(wh, str):
            vehicle.window_heatings.heating_state._set_value(  # pylint: disable=protected-access
                WINDOW_HEATING_MAPPING.get(wh, WindowHeatings.HeatingState.UNKNOWN), measured=captured_at)

        # Maintenance intervals. The portal encodes a signed countdown: a negative
        # value is the amount still remaining, zero is due, a positive value is
        # overdue. Expose the time interval as a concrete due date (which conveys
        # overdue naturally as a past date) and the distance as remaining km.
        # The bootstrap-merged dataset can lack a capture time, so anchor the due
        # date on "now" when captured_at is absent.
        date_anchor = captured_at or datetime.now(tz=timezone.utc)
        insp_days = dataset.value_of('maintenance_interval__time_until_inspection')
        if insp_days is not None:
            vehicle.maintenance.inspection_due_at._set_value(  # pylint: disable=protected-access
                value=date_anchor + timedelta(days=-insp_days), measured=captured_at)
        oil_days = dataset.value_of('maintenance_interval__time_until_oil_change')
        if oil_days is not None:
            vehicle.maintenance.oil_service_due_at._set_value(  # pylint: disable=protected-access
                value=date_anchor + timedelta(days=-oil_days), measured=captured_at)
        insp_dist = dataset.value_of('maintenance_interval_distance_until_inspection')
        if insp_dist is not None:
            vehicle.maintenance.inspection_due_after._set_value(  # pylint: disable=protected-access
                value=abs(insp_dist), measured=captured_at, unit=Length.KM)
        oil_dist = dataset.value_of('maintenance_interval_distance_until_oil_change')
        if oil_dist is not None:
            vehicle.maintenance.oil_service_due_after._set_value(  # pylint: disable=protected-access
                value=abs(oil_dist), measured=captured_at, unit=Length.KM)

        # Outside (ambient) temperature, reported in deci-Kelvin.
        outside = decikelvin_to_celsius(dataset.value_of('outside_temperature'))
        if outside is not None:
            vehicle.outside_temperature._set_value(value=outside, measured=captured_at, unit=Temperature.C)  # pylint: disable=protected-access

        # Remaining climatisation time -> estimated completion date. The dotted
        # format delivers "<seconds>s"; the flat PHEV format delivers integer
        # minutes (remaining_climatisation_time).
        clim_seconds = dataset.value_of('remaining_climate_time')
        clim_minutes = dataset.value_of('remaining_climatisation_time')
        if clim_seconds is not None:
            vehicle.climatization.estimated_date_reached._set_value(  # pylint: disable=protected-access
                value=date_anchor + timedelta(seconds=clim_seconds), measured=captured_at)
        elif clim_minutes is not None:
            vehicle.climatization.estimated_date_reached._set_value(  # pylint: disable=protected-access
                value=date_anchor + timedelta(minutes=clim_minutes), measured=captured_at)

        # Doors, windows and lights status (applies to all vehicles).
        self._map_status(vehicle, dataset, captured_at)

        # Parking brake (0 = released, 1 = engaged). parking_brake exists on the
        # vehicle only since the carconnectivity release that added it, so guard
        # with hasattr to stay compatible with older cores.
        parking_brake = dataset.value_of('parking_brake')
        if parking_brake in (0, 1) and hasattr(vehicle, 'parking_brake'):
            vehicle.parking_brake._set_value(value=bool(parking_brake), measured=captured_at)  # pylint: disable=protected-access

        # Drive slots follow the portal's primary/secondary engines (same convention
        # as the official seatcupra connector): on a PHEV the primary engine is the
        # combustion one and the secondary is electric; a pure EV has only the
        # primary (electric) slot.
        electric_drive_id = 'secondary' if is_phev else 'primary'
        if isinstance(vehicle, ElectricVehicle):
            self._map_electric(vehicle, dataset, captured_at, electric_drive_id)

            drive = vehicle.get_electric_drive()
            if drive is None:
                drive = ElectricDrive(drive_id=electric_drive_id, drives=vehicle.drives,
                                      initialization=vehicle.drives.get_initialization(electric_drive_id))
                drive.type._set_value(GenericDrive.Type.ELECTRIC)  # pylint: disable=protected-access
                vehicle.drives.add_drive(drive)

            # Flat-format eGolf fields: state_of_charge -> drive level,
            # cruising_range_primary_engine -> drive range.
            soc = dataset.value_of('state_of_charge')
            if soc is not None:
                drive.level._set_value(value=soc, measured=captured_at)  # pylint: disable=protected-access
                drive.level.precision = 1

            # On a PHEV the electric range is the *secondary* engine; on a pure EV
            # it is reported as the primary engine.
            e_range = dataset.value_of('cruising_range_secondary_engine') if is_phev \
                else dataset.value_of('cruising_range_primary_engine')
            if e_range is not None:
                drive.range._set_value(value=e_range, measured=captured_at, unit=Length.KM)  # pylint: disable=protected-access
                drive.range.precision = 1

            # Some flat-format datasets only provide a bare 'mileage' field.
            flat_mileage = dataset.freshest_max_value_of('mileage')
            if flat_mileage is not None and mileage is None:
                vehicle.odometer._set_value(value=flat_mileage, measured=captured_at, unit=Length.KM)  # pylint: disable=protected-access
                vehicle.odometer.precision = 1

        if isinstance(vehicle, CombustionVehicle):
            self._map_combustion(vehicle, dataset, captured_at)

        # Combined (total) range across all drives, when the portal reports it
        # directly (the seatcupra connector instead sums the per-engine ranges).
        combined = dataset.value_of('cruising_range_combined')
        if combined is not None:
            vehicle.drives.total_range._set_value(value=combined, measured=captured_at, unit=Length.KM)  # pylint: disable=protected-access
            vehicle.drives.total_range.precision = 1

    def _map_electric(self, vehicle: VWEudaElectricVehicle, dataset: Dataset,
                      captured_at: "Optional[datetime]", drive_id: str = 'primary') -> None:
        """Map EV-specific fields (SoC, charging, battery temps, range)."""
        drive = vehicle.get_electric_drive()
        if drive is None:
            drive = ElectricDrive(drive_id=drive_id, drives=vehicle.drives,
                                  initialization=vehicle.drives.get_initialization(drive_id))
            drive.type._set_value(GenericDrive.Type.ELECTRIC)  # pylint: disable=protected-access
            vehicle.drives.add_drive(drive)

        # State of charge -> drive level (%)
        soc = dataset.value_of('battery_state_report.soc')
        if soc is not None:
            drive.level._set_value(value=soc, measured=captured_at)  # pylint: disable=protected-access
            drive.level.precision = 1

        # Estimated range (km) - frequently absent from EU Data Act datasets.
        drive_range = dataset.value_of('range')
        if drive_range is not None:
            drive.range._set_value(value=drive_range, measured=captured_at, unit=Length.KM)  # pylint: disable=protected-access
            drive.range.precision = 1

        # Battery temperature min/max (°C)
        battery: Battery = drive.battery
        tmin = dataset.value_of('min_temperature')
        if tmin is not None:
            battery.temperature_min._set_value(value=tmin, measured=captured_at, unit=Temperature.C)  # pylint: disable=protected-access
        tmax = dataset.value_of('max_temperature')
        if tmax is not None:
            battery.temperature_max._set_value(value=tmax, measured=captured_at, unit=Temperature.C)  # pylint: disable=protected-access

        # Maximal (usable) battery energy content -> available_capacity (kWh).
        # The portal reports energy_contents.maximal_energy_content.<leaf>: the
        # dynamically measured usable capacity (degrades with battery age), the
        # same concept the skoda connector fills from the static spec, so it backs
        # a derivable state of health = available_capacity / total_capacity.
        # Matched by prefix because the exact leaf is unconfirmed, which also skips
        # the companion value_type enum. NOTE: the /10 scaling (deci-kWh) follows
        # the request in issue #22 and is unverified against a real value. Absent
        # on many vehicles (guarded).
        max_energy = dataset.freshest_numeric_by_prefix('energy_contents.maximal_energy_content')
        if isinstance(max_energy, (int, float)):
            battery.available_capacity._set_value(  # pylint: disable=protected-access
                value=max_energy / 10, measured=captured_at, unit=Energy.KWH)

        # Charging power (kW)
        power = dataset.value_of('battery_state_report.charge_power')
        if power is not None:
            vehicle.charging.power._set_value(value=power, measured=captured_at, unit=Power.KW)  # pylint: disable=protected-access

        # Charging state
        charge_state = dataset.value_of('charging_state_report.current_charge_state')
        if isinstance(charge_state, str):
            vehicle.charging.state._set_value(  # pylint: disable=protected-access
                CHARGE_STATE_MAPPING.get(charge_state, Charging.ChargingState.UNKNOWN), measured=captured_at)

        # Charge type (what the car is plugged into: AC / DC / off)
        charge_type = dataset.value_of('charging_state_report.charge_type')
        if isinstance(charge_type, str):
            vehicle.charging.type._set_value(  # pylint: disable=protected-access
                CHARGE_TYPE_MAPPING.get(charge_type, Charging.ChargingType.UNKNOWN), measured=captured_at)

        # Charge rate (range gained over time). The unit comes from the companion
        # charge_rate_unit enum (km/mi, per-h/min); normalise to a per-hour speed.
        charge_rate = dataset.value_of('battery_state_report.charge_rate')
        if charge_rate is not None:
            rate_value, rate_unit = _charge_rate_per_hour(
                charge_rate, dataset.value_of('battery_state_report.charge_rate_unit'))
            vehicle.charging.rate._set_value(value=rate_value, measured=captured_at, unit=rate_unit)  # pylint: disable=protected-access

        # Remaining time to a full charge -> estimated completion timestamp
        # (the native attribute is a date, so add the remaining seconds to the
        # capture time rather than exposing a raw duration).
        remaining = dataset.value_of('battery_state_report.remaining_charging_time_complete')
        if remaining is not None and captured_at is not None:
            vehicle.charging.estimated_date_reached._set_value(  # pylint: disable=protected-access
                value=captured_at + timedelta(seconds=remaining), measured=captured_at)

        # Target state of charge (%) - read-only here (no commands possible).
        target_soc = dataset.value_of('settings.target_soc')
        if target_soc is not None:
            vehicle.charging.settings.target_level._set_value(value=target_soc, measured=captured_at)  # pylint: disable=protected-access

        # Selected charge mode (charge_mode_selection). The dotted format carries a
        # single value; the flat/continuous format splits it into one boolean per
        # option, of which the active one is set. Neutral name `charge_mode`: the
        # field is the *selected* mode (one value being `preferred_charging_times`),
        # not necessarily a "preferred" one. Read-only, no commands here. The
        # attribute is created lazily and tagged connector_custom (no core model).
        charge_mode = _charge_mode(dataset.value_of('settings.charge_mode_selection'))
        if charge_mode is None:
            charge_mode = _charge_mode_flat(dataset)
        if charge_mode is not None:
            settings = vehicle.charging.settings
            charge_mode_attr = getattr(settings, 'charge_mode', None)
            if not isinstance(charge_mode_attr, EnumAttribute):
                charge_mode_attr = EnumAttribute(name='charge_mode', parent=settings,
                                                 value_type=VWEudaChargeMode, tags={'connector_custom'})
                settings.charge_mode = charge_mode_attr
            charge_mode_attr._set_value(charge_mode, measured=captured_at)  # pylint: disable=protected-access

        # --- Flat-format charging fields (eGolf / PHEV) ----------------------
        # Mirror the dotted battery_state_report.* / charging_state_report.* fields
        # above but use simple lower-case string enums; map them when the dotted
        # variants are absent. Their values match the CarConnectivity enum values.
        flat_state = dataset.value_of('charging_state')
        if isinstance(flat_state, str) and charge_state is None:
            try:
                state_enum = Charging.ChargingState(flat_state.strip().lower())
            except ValueError:
                state_enum = Charging.ChargingState.UNKNOWN
            vehicle.charging.state._set_value(state_enum, measured=captured_at)  # pylint: disable=protected-access

        flat_mode = dataset.value_of('charging_mode')
        if isinstance(flat_mode, str) and charge_type is None:
            try:
                type_enum = Charging.ChargingType(flat_mode.strip().lower())
            except ValueError:
                type_enum = Charging.ChargingType.UNKNOWN
            vehicle.charging.type._set_value(type_enum, measured=captured_at)  # pylint: disable=protected-access

        # Flat-format charge power: a deci-kW integer (e.g. 99 -> 9.9 kW on
        # Passat/Tayron/Golf PHEV). Mapped only when the dotted
        # battery_state_report.charge_power (already scaled kW) is absent, so the
        # dotted behaviour is untouched.
        flat_power = dataset.value_of('charging_power')
        if isinstance(flat_power, (int, float)) and power is None:
            vehicle.charging.power._set_value(value=flat_power / 10, measured=captured_at, unit=Power.KW)  # pylint: disable=protected-access

        # Flat-format charge rate: same deci scaling; the unit comes from the flat
        # charge_rate_unit companion (km/mi, per-h/min), normalised to a per-hour
        # speed. Mapped only when the dotted battery_state_report.charge_rate is absent.
        flat_rate = dataset.value_of('actual_charge_rate')
        if isinstance(flat_rate, (int, float)) and charge_rate is None:
            rate_value, rate_unit = _charge_rate_per_hour(flat_rate / 10, dataset.value_of('charge_rate_unit'))
            vehicle.charging.rate._set_value(value=rate_value, measured=captured_at, unit=rate_unit)  # pylint: disable=protected-access

        plug = dataset.value_of('plug_state')
        if isinstance(plug, str):
            try:
                vehicle.charging.connector.connection_state._set_value(  # pylint: disable=protected-access
                    ChargingConnector.ChargingConnectorConnectionState(plug.strip().lower()), measured=captured_at)
            except ValueError:
                pass

        ext_power = dataset.value_of('external_power_supply_state')
        if isinstance(ext_power, str):
            try:
                vehicle.charging.connector.external_power._set_value(  # pylint: disable=protected-access
                    ChargingConnector.ExternalPower(ext_power.strip().lower()), measured=captured_at)
            except ValueError:
                pass

        # Flat remaining charging time is in MINUTES; 65535 is the "no value" sentinel.
        flat_remaining = dataset.value_of('remaining_charging_time')
        if isinstance(flat_remaining, (int, float)) and 0 <= flat_remaining < 65535 and remaining is None:
            anchor = captured_at or datetime.now(tz=timezone.utc)
            vehicle.charging.estimated_date_reached._set_value(  # pylint: disable=protected-access
                value=anchor + timedelta(minutes=flat_remaining), measured=captured_at)

        # Average electric consumption (long term): portal reports kWh/1000km,
        # divide by 10 for kWh/100km.
        consumption = dataset.value_of('long_term_data_average_electr_engine_consumption')
        if isinstance(consumption, (int, float)):
            drive.consumption._set_value(  # pylint: disable=protected-access
                value=round(consumption / 10, 1), measured=captured_at, unit=EnergyConsumption.KWH100KM)

    def _map_status(self, vehicle: "VWEudaVehicle", dataset: Dataset,
                    captured_at: "Optional[datetime]") -> None:
        """Map per-door / per-window open+lock state and lights onto CarConnectivity."""
        # Overall central lock (flat string field).
        lock = dataset.value_of('lock_state')
        if isinstance(lock, str):
            text = lock.strip().lower()
            if text == 'locked':
                vehicle.doors.lock_state._set_value(Doors.LockState.LOCKED, measured=captured_at)  # pylint: disable=protected-access
            elif text == 'unlocked':
                vehicle.doors.lock_state._set_value(Doors.LockState.UNLOCKED, measured=captured_at)  # pylint: disable=protected-access

        # Per-door open + lock state.
        for door_id, (open_f, lock_f) in _DOOR_FIELDS.items():
            open_code = _open_code(dataset.value_of(open_f))
            lock_code = _lock_code(dataset.value_of(lock_f))
            if open_code is None and lock_code is None:
                continue
            door = vehicle.doors.doors.get(door_id)
            if door is None:
                door = Doors.Door(door_id=door_id, doors=vehicle.doors)
                door.enabled = True
                vehicle.doors.doors[door_id] = door
            if open_code is not None:
                door.open_state._set_value(Doors.OpenState(open_code), measured=captured_at)  # pylint: disable=protected-access
            if lock_code is not None:
                door.lock_state._set_value(Doors.LockState(lock_code), measured=captured_at)  # pylint: disable=protected-access
        if vehicle.doors.doors:
            vehicle.doors.enabled = True

        # Per-window open state, preferring the opening percentage (which also
        # surfaces an ajar window) over the coarse open/closed code.
        for window_id, (position_f, state_f) in _WINDOW_FIELDS.items():
            open_code = _window_open_code(dataset.value_of(position_f), dataset.value_of(state_f))
            if open_code is None:
                continue
            window = vehicle.windows.windows.get(window_id)
            if window is None:
                window = Windows.Window(window_id=window_id, windows=vehicle.windows)
                window.enabled = True
                vehicle.windows.windows[window_id] = window
            window.open_state._set_value(Windows.OpenState(open_code), measured=captured_at)  # pylint: disable=protected-access
        if vehicle.windows.windows:
            vehicle.windows.enabled = True

        # Parking lights.
        light_code = _light_code(dataset.value_of('parking_lights'))
        if light_code is not None:
            light = vehicle.lights.lights.get('parking')
            if light is None:
                light = Lights.Light(light_id='parking', lights=vehicle.lights)
                light.enabled = True
                vehicle.lights.lights['parking'] = light
            light.light_state._set_value(Lights.LightState(light_code), measured=captured_at)  # pylint: disable=protected-access
            vehicle.lights.enabled = True

        # Per-window heating (front / rear); the flat fields carry "on" / "off".
        for window_id, field in (('front', 'window_heating_state_front'),
                                  ('rear', 'window_heating_state_rear')):
            wh = dataset.value_of(field)
            if not isinstance(wh, str):
                continue
            try:
                state = WindowHeatings.HeatingState(wh.strip().lower())
            except ValueError:
                state = WindowHeatings.HeatingState.UNKNOWN
            heater = vehicle.window_heatings.windows.get(window_id)
            if heater is None:
                heater = WindowHeatings.WindowHeating(window_id=window_id,
                                                      window_heatings=vehicle.window_heatings)
                heater.enabled = True
                vehicle.window_heatings.windows[window_id] = heater
            heater.heating_state._set_value(state, measured=captured_at)  # pylint: disable=protected-access
        if vehicle.window_heatings.windows:
            vehicle.window_heatings.enabled = True

    def _map_combustion(self, vehicle: "VWEudaVehicle", dataset: Dataset,
                        captured_at: "Optional[datetime]") -> None:
        """Map combustion-engine fields (fuel level, petrol range and consumption)."""
        # The portal has no fuel-type field, so infer a diesel from a *numeric* SCR
        # (AdBlue) range: petrol/PHEV cars also carry the scr_range field but report
        # it as an empty string. A diesel needs a DieselDrive because adblue_range
        # only exists there (a plain CombustionDrive would raise AttributeError).
        adblue_range = dataset.value_of('scr_range')
        is_diesel = isinstance(adblue_range, (int, float))

        # The combustion engine is the portal's primary engine (matching the
        # seatcupra convention where the primary slot is the fuel engine on a PHEV).
        drive = vehicle.get_combustion_drive()
        if drive is None:
            if is_diesel:
                drive = DieselDrive(drive_id='primary', drives=vehicle.drives,
                                    initialization=vehicle.drives.get_initialization('primary'))
                drive.type._set_value(GenericDrive.Type.DIESEL)  # pylint: disable=protected-access
            else:
                drive = CombustionDrive(drive_id='primary', drives=vehicle.drives,
                                        initialization=vehicle.drives.get_initialization('primary'))
                drive.type._set_value(GenericDrive.Type.GASOLINE)  # pylint: disable=protected-access
            vehicle.drives.add_drive(drive)

        # Fuel level (%): prefer the dedicated current level, fall back to tank level.
        fuel = dataset.value_of('fuel_level_current_level')
        if fuel is None:
            fuel = dataset.value_of('tank_current_level')
        if isinstance(fuel, (int, float)):
            drive.level._set_value(value=fuel, measured=captured_at)  # pylint: disable=protected-access
            drive.level.precision = 1

        # Petrol (combustion) range = the primary engine on a PHEV.
        fuel_range = dataset.value_of('cruising_range_primary_engine')
        if fuel_range is not None:
            drive.range._set_value(value=fuel_range, measured=captured_at, unit=Length.KM)  # pylint: disable=protected-access
            drive.range.precision = 1

        # Average fuel consumption (long term): portal reports L/1000km, /10 -> L/100km.
        consumption = dataset.value_of('long_term_data_average_fuel_consumption')
        if isinstance(consumption, (int, float)):
            drive.consumption._set_value(  # pylint: disable=protected-access
                value=round(consumption / 10, 1), measured=captured_at, unit=FuelConsumption.L100KM)

        # Engine oil level (%). oil_level lives on CombustionDrive in carconnectivity,
        # but only since the release that added it, so guard with hasattr to stay
        # compatible with older cores (the attribute is simply skipped there).
        oil = dataset.value_of('oil_level_actual_level')
        if isinstance(oil, (int, float)) and hasattr(drive, 'oil_level'):
            drive.oil_level._set_value(value=oil, measured=captured_at)  # pylint: disable=protected-access
            drive.oil_level.precision = 0.1

        # SCR / AdBlue range (diesel only; empty on petrol / PHEV). adblue_range
        # exists only on DieselDrive, so guard exactly like the official connectors.
        if is_diesel and isinstance(drive, DieselDrive):
            drive.adblue_range._set_value(  # pylint: disable=protected-access
                value=adblue_range, measured=captured_at, unit=Length.KM)
            drive.adblue_range.precision = 1

    # -- scheduling --------------------------------------------------------

    def _reschedule(self, next_polls: "List[datetime]") -> None:
        """Set the next interval ~15 min after the newest dataset, else short retry."""
        if next_polls:
            target = min(next_polls)
            delta = target - datetime.now(tz=timezone.utc)
            if delta > MIN_INTERVAL:
                self.interval._set_value(delta)  # pylint: disable=protected-access
                LOG.debug('Next refresh in %s', delta)
                return
        self.interval._set_value(RETRY_INTERVAL)  # pylint: disable=protected-access
        LOG.debug('Next dataset overdue; retrying in %s', RETRY_INTERVAL)

    # -- metadata ----------------------------------------------------------

    def get_version(self) -> str:
        return __version__

    def get_type(self) -> str:
        return "carconnectivity-connector-vw-eu-data-act"

    def get_name(self) -> str:
        return "Volkswagen EU Data Act Connector"
